name: Assiny Scraper Automation

on:
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Usar uma versão específica do Python

      - name: Cache de dependências Pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache do Playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Rodar scraping
        run: python assiny_scraper.py
        env:
          STORAGE_STATE_JSON: ${{ secrets.STORAGE_STATE_JSON }}

      - name: Commit e push do CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add valor_assiny.csv
          
          # Apenas commita se houver alterações no arquivo
          if ! git diff --staged --quiet; then
            git commit -m "Update valor_assiny.csv"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          else
            echo "Nenhuma alteração para commitar."
          fi
